#!/bin/sh

ben () {
	clear
	#strip all numbers except for the first through entire dataset and remove all 0s
	cut -c 1 "$1" | sed "s/0//g" > "$HOME"/.local/tmp/benford.txt
	
	#count and print number of values
	echo "##################"
	printf "Dataset size: "
	cat "$HOME"/.local/tmp/benford.txt | wc -l
	echo "##################"
	
	#find quantities of each number 1 to 9
	echo "Quantity of 1:"
	grep -c "1" "$HOME"/.local/tmp/benford.txt
	echo ""
	echo "Quantity of 2:"
	grep -c "2" "$HOME"/.local/tmp/benford.txt
	echo ""
	echo "Quantity of 3:"
	grep -c "3" "$HOME"/.local/tmp/benford.txt
	echo ""
	echo "Quantity of 4:"
	grep -c "4" "$HOME"/.local/tmp/benford.txt
	echo ""
	echo "Quantity of 5:"
	grep -c "5" "$HOME"/.local/tmp/benford.txt
	echo ""
	echo "Quantity of 6:"
	grep -c "6" "$HOME"/.local/tmp/benford.txt
	echo ""
	echo "Quantity of 7:"
	grep -c "7" "$HOME"/.local/tmp/benford.txt
	echo ""
	echo "Quantity of 8:"
	grep -c "8" "$HOME"/.local/tmp/benford.txt
	echo ""
	echo "Quantity of 9:"
	grep -c "9" "$HOME"/.local/tmp/benford.txt
	echo "##################"
}

ben_help () {
	printf "Benford's Law Tester by swindlesmccoop
	
Usage: benford [-h] [dataset]
	
[dataset]: Prints data for [dataset]
-h. --help: Display this help message
" && exit 1
}

#if no parameters supplied, print help msg
[ -z $1 ] && ben_help
case "$1" in
	-h) ben_help ;;
	--help) ben_help ;;
	*) ben "$@" ;;
esac
